# Generated by Django 5.2.3 on 2025-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('owner', 'Futsal Owner')], max_length=10),
        ),
    ]
