# Generated by Django 5.2.3 on 2025-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_goalkeeper',
            field=models.BooleanField(default=False),
        ),
    ]
