# Generated by Django 5.2.3 on 2025-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0002_player_is_goalkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals_team_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_team_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
