# Generated by Django 5.2.3 on 2025-07-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
