# Generated by Django 5.2.3 on 2025-09-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0003_match_goals_team_1_match_goals_team_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rejections', to='futsal_app.team')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_rejections', to='futsal_app.team')),
            ],
        ),
    ]
