# Generated by Django 5.2.4 on 2025-07-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0003_teammatch_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='futsal_app.teammatch')),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='futsal_app.futsal')),
            ],
        ),
    ]
