# Generated by Django 5.2.3 on 2025-10-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0004_rejectedinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cleared', models.BooleanField(default=False)),
                ('rejected_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_team', to='futsal_app.team')),
                ('rejecting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_by', to='futsal_app.team')),
            ],
            options={
                'unique_together': {('rejecting_team', 'rejected_team')},
            },
        ),
    ]
