# Generated by Django 5.2.4 on 2025-07-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='futsal_app.timeslot'),
        ),
    ]
