# Generated by Django 5.2.4 on 2025-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0007_teammatch_result_updated_teammatch_team_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed')], default='available', max_length=20),
        ),
    ]
