# Generated by Django 5.2.4 on 2025-07-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0008_timeslot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='team_1_score',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team_2_score',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='status',
        ),
    ]
