# Generated by Django 5.2.4 on 2025-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal_app', '0009_remove_teammatch_team_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='team_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
